name: workflow1
on:
  workflow_dispatch:
   inputs:
     env:
        type: string
        required: true
jobs:
  workflow-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
